iso_canton_to_region = {
    'CH': 0,
    'CHFL': -1,
    'AG': 3,
    'AI': 5,
    'AR': 5,
    'BE': 2,
    'BL': 3,
    'BS': 3,
    'FL': -1,
    'FR': 2,
    'GE': 1,
    'GL': 5,
    'GR': 6,
    'JU': 2,
    'LU': 4,
    'NE': 1,
    'NW': 4,
    'OW': 4,
    'SG': 5,
    'SH': 5,
    'SO': 3,
    'SZ': 4,
    'TG': 5,
    'TI': 6,
    'UR': 4,
    'VD': 1,
    'VS': 1,
    'ZG': 4,
    'ZH': 5
}

name_to_region = {
    'Basel-Stadt': 3,
    'Solothurn': 3,
    'Aargau': 3,
    'Vaud': 1,
    'Bern': 2,
    'Basel-Land': 3,
    'Basel-Landschaft': 3,
    'Zürich': 5,
    'Schwyz': 4,
    'Thurgau': 5,
    'Neuchâtel': 1,
    'Schaffhausen': 5,
    'Lucerne': 4,
    'Graubünden': 6,
    'Uri': 4,
    'Geneva': 1,
    'Ticino': 6,
    'Valais': 1,
    'Sankt Gallen': 5,
    'Switzerland': 0,
    'Obwalden': 4,
    'Jura': 2,
    'Fribourg': 2,
    'Zug': 4,
    'Glarus': 5,
    'Nidwalden': 4,
    'Appenzell Ausserrhoden': 5,
    'Appenzell Innerrhoden': 5,
}
