name: daily-update

on:
  schedule:
    - cron: "14 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: download new data
        run: python main.py -d

      - name: query mutations
        run: python scripts/mutation_proportions.py

      - name: update latest plots
        run: python daily.py

      - name: commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
