name: daily-update

on:
  schedule:
    - cron: "14 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.11"

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: download new data
        run: python main.py -d

      - name: update latest plots
        run: python daily.py

      - name: query mutations
        run: python scripts/mutation_proportions.py

      - name: commit updates
        uses: stefanzweifel/git-auto-commit-action@v5
